#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst_n", 1, hls_in, -1, "", "", 1),
	Port_Property("arvalid_V", 1, hls_in, 0, "ap_none", "in_data", 1),
	Port_Property("arready_V", 1, hls_in, 1, "ap_none", "in_data", 1),
	Port_Property("rvalid_V", 1, hls_in, 2, "ap_none", "in_data", 1),
	Port_Property("rready_V", 1, hls_in, 3, "ap_none", "in_data", 1),
	Port_Property("wvalid_V", 1, hls_in, 4, "ap_none", "in_data", 1),
	Port_Property("wready_V", 1, hls_in, 5, "ap_none", "in_data", 1),
	Port_Property("wlast_V", 1, hls_in, 6, "ap_none", "in_data", 1),
	Port_Property("bvalid_V", 1, hls_in, 7, "ap_none", "in_data", 1),
	Port_Property("bready_V", 1, hls_in, 8, "ap_none", "in_data", 1),
	Port_Property("s_axi_timestamp_AWVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_timestamp_AWREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_timestamp_AWADDR", 32, hls_in, -1, "", "", 1),
	Port_Property("s_axi_timestamp_WVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_timestamp_WREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_timestamp_WDATA", 32, hls_in, -1, "", "", 1),
	Port_Property("s_axi_timestamp_WSTRB", 4, hls_in, -1, "", "", 1),
	Port_Property("s_axi_timestamp_ARVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_timestamp_ARREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_timestamp_ARADDR", 32, hls_in, -1, "", "", 1),
	Port_Property("s_axi_timestamp_RVALID", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_timestamp_RREADY", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_timestamp_RDATA", 32, hls_out, -1, "", "", 1),
	Port_Property("s_axi_timestamp_RRESP", 2, hls_out, -1, "", "", 1),
	Port_Property("s_axi_timestamp_BVALID", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_timestamp_BREADY", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_timestamp_BRESP", 2, hls_out, -1, "", "", 1),
};
const char* HLS_Design_Meta::dut_name = "axi_timestamper";
